spring.application.name=progreso2-juliana-sosa
server.port=8081

spring.rabbitmq.host=cougar.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=[USER_NAME]
spring.rabbitmq.password=[PASSWORD]

spring.rabbitmq.virtual-host=[VIRTUAL_HOST]